### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by juliohm** [UCL/LatBo.jl#17]
Is there any documentation available for the package? It looks really promising!

If by any chance you could illustrate how to simulate 2D shallow water flow, that would be incredibly helpful: https://en.wikipedia.org/wiki/Shallow_water_equations

**Comment by mdavezac** [comment]
For usage, the documentation is limited to the example in the example directory.
For the api, the unit tests  are the documentation.

I have not looked at the shallow water equations too closely, but it seems it requires a forcing term and probably some modified boundary conditions. That could be done by overloading `streaming` with new corresponding types (as in `streaming.jl`). And then setting up the kernels (a.k.a. playpen) to reference the new streamer and boundary types (as done in `lbgk` in `lbgk.jl`)

Unfortunately, this is a package looking for an active developer. I'm happy to help if you want to take it further :)

As a side note, the current implementation of the main loop is likely not  type stable. This probably has a fair impact on performance since the loops are fairly tight.

**Comment by juliohm** [comment]
Thanks @mdavezac , I am not qualified for taking it, I was just wondering if it could be done easily already. I will close the issue, thank you anyways. :)

Hope you will find the time to keep working on the project, or find someone that can help.

Cheers,
